baseURL = "https://mamstr.com"
languageCode = "en-us"
theme = "resto-hugo"
title = "Mamstr"

copyright = "&copy 2021 Mamstr"
[params]
logo = "img/launch_image.png"
enableDisqus = true
footerText = "See you on the app soon...."